import { Inter } from "next/font/google";
import Head from 'next/head';
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vashisht",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className={inter.className}>
        <div className="inner_retangle_main">


        <ul className="circles">
                <li></li>
                <li></li> 
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
        </ul>

       <div class="wave"></div>
       <div class="wave"></div>
       <div class="wave"></div>

          {children}
        </div>
      </body>
    </html>
  );
}
